### ISSUE TITLE
Cached image from Redis is not displayed in Linux + .NET Core

### ISSUE THREAD

**Issue by fcatae** [DXBrazil/Arda#16]

**Comment by fcatae** [comment]
In the default deployment, user picture should be used. Is it a bug?

**Comment by fcatae** [comment]
I can reproduce the problem in Linux + NetCore.

Problem:
https://github.com/StackExchange/StackExchange.Redis/issues/410
https://github.com/aspnet/Caching/issues/260
https://github.com/StackExchange/StackExchange.Redis/issues/463

Long explanation:
https://github.com/dotnet/corefx/issues/5829

**Comment by fcatae** [comment]
The workaround is to resolve the IP address before creating the ConnectionMultiplexer. This has the downside that if the Redis machine changes the IP, then we have to restart the client. 
Since we are using docker, and IP change is quite common, the best workaround seems to be using static IP address.

**Comment by fcatae** [comment]
Using this configuration in docker-compose.yml
```
...
networks:
  ardanet:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
```
